/*
  components/ShareCard.js — Day 6

  A compact summary card with a shareable link.
  Clicking "Copy link" writes a URL like:
    https://devpulse.app/?u=torvalds
  to the clipboard — so anyone can share their profile.

  Also includes a "Download summary" button that generates a
  plain text .txt file of the recruiter summary — useful to
  attach to a job application or paste into LinkedIn.
*/

import React, { useState } from 'react';
import './ShareCard.css';

export default function ShareCard({ profile, score, languages, summary }) {
  const [copied, setCopied] = useState(false);

  const shareUrl = `${window.location.origin}?u=${profile.login}`;

  const handleCopyLink = () => {
    navigator.clipboard.writeText(shareUrl).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }).catch(() => {});
  };

  const handleDownload = () => {
    const topLangs = languages.slice(0, 3).map(l => l.language).join(', ');
    const lines = [
      `DevPulse Profile — ${profile.name} (@${profile.login})`,
      `${'─'.repeat(50)}`,
      '',
      `Score:        ${score.total}/100 (${score.label})`,
      `Repos:        ${profile.publicRepos} public`,
      `Followers:    ${profile.followers}`,
      `Stars earned: ${summary.totalStars}`,
      `Top languages: ${topLangs || 'n/a'}`,
      '',
      `GitHub:  ${profile.htmlUrl}`,
      `Profile: ${shareUrl}`,
      '',
      `Generated by DevPulse — github.com/YOUR_USERNAME/devpulse`,
    ];

    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = `${profile.login}-devpulse.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="share-card card fade-in">
      <div className="share-card-header">
        <div>
          <h2 className="share-title">Share your profile</h2>
          <p className="share-sub">Send this link to anyone — no login required</p>
        </div>
      </div>

      <div className="share-url-row">
        <span className="share-url">{shareUrl}</span>
        <button className="share-copy-btn" onClick={handleCopyLink}>
          {copied ? 'Copied' : 'Copy link'}
        </button>
      </div>

      <div className="share-actions">
        <button className="share-action-btn" onClick={handleDownload}>
          Download summary (.txt)
        </button>
        <a
          className="share-action-btn share-action-btn--outline"
          href={profile.htmlUrl}
          target="_blank"
          rel="noreferrer"
        >
          View on GitHub
        </a>
      </div>
    </div>
  );
}
